# Changelog

All notable changes to this project will be documented in this file.
This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
Je suis le header de la release héhéhé
### Changed

- release: bump version for release
- more map


## [0.1.0]

### Added

- more map

### Changed

- release: bump version for release

### Fixed

- stdout as argument in [#13](https://github.com/wiiznokes/changelog-generator/pull/13) by [@wiiznokes](https://github.com/wiiznokes)
- release not in order (#14) in [#14](https://github.com/wiiznokes/changelog-generator/pull/14) by [@wiiznokes](https://github.com/wiiznokes)

Full Changelog: https://github.com/wiiznokes/changelog-generator/compare/v0.1.1...v0.1.2
